IN-CORE/incore-helm

- Chart.yaml
- README.md
- values.yaml
Release 1.22.1 for incore 4.8.1
incore docs 4.8.1
incore api doc 4.8.1
pyincore doc 1.15.1
incore-lab 1.2.1
> Release 1.22.1

- Chart.yaml
- README.md
- templates/auth/deployment.yaml
Added mongodb URI to incore-auth's deployment as environment variable
> Add mongodb uri to incore auth

- README.md
- playbook-configs/galveston/map.config.json
- playbook-configs/joplin/map.config.json
- playbook-configs/slc/map.config.json
Reverts IN-CORE/incore-helm#98
> Revert "Map zoom level changes"

- README.md
- playbook-configs/galveston/datawolfWorkflow.config.dev.json
- playbook-configs/galveston/datawolfWorkflow.config.prod.json
- playbook-configs/galveston/globals.config.dev.json
- playbook-configs/galveston/globals.config.prod.json
- playbook-configs/galveston/map.config.json
- playbook-configs/joplin/datawolfWorkflow.config.dev.json
- playbook-configs/joplin/datawolfWorkflow.config.prod.json
- playbook-configs/joplin/globals.config.dev.json
- playbook-configs/joplin/globals.config.prod.json
- playbook-configs/joplin/map.config.json
- playbook-configs/slc/datawolfWorkflow.config.dev.json
- playbook-configs/slc/datawolfWorkflow.config.prod.json
- playbook-configs/slc/globals.config.dev.json
- playbook-configs/slc/globals.config.prod.json
- playbook-configs/slc/map.config.json
update some configuration that works with incore-playbook 0.6.0
> 337 release incore playbook 060 and update config for each city playbooks

- README.md
- playbook-configs/galveston/datawolfRS.config.dev.json
- playbook-configs/galveston/datawolfRS.config.prod.json
- playbook-configs/galveston/datawolfRSWorkflow.config.dev.json
- playbook-configs/galveston/datawolfRSWorkflow.config.prod.json
- playbook-configs/galveston/datawolfWorkflow.config.dev.json
- playbook-configs/galveston/datawolfWorkflow.config.prod.json
- playbook-configs/galveston/globals.config.dev.json
- playbook-configs/galveston/globals.config.prod.json
- playbook-configs/galveston/map.config.json
- playbook-configs/joplin/datawolfRS.config.dev.json
- playbook-configs/joplin/datawolfRS.config.prod.json
- playbook-configs/joplin/datawolfRSWorkflow.config.dev.json
- playbook-configs/joplin/datawolfRSWorkflow.config.prod.json
- playbook-configs/joplin/datawolfWorkflow.config.dev.json
- playbook-configs/joplin/datawolfWorkflow.config.prod.json
- playbook-configs/joplin/globals.config.dev.json
- playbook-configs/joplin/globals.config.prod.json
- playbook-configs/joplin/map.config.json
- playbook-configs/slc/datawolfRS.config.dev.json
- playbook-configs/slc/datawolfRS.config.prod.json
- playbook-configs/slc/datawolfRSWorkflow.config.dev.json
- playbook-configs/slc/datawolfRSWorkflow.config.prod.json
- playbook-configs/slc/datawolfWorkflow.config.dev.json
- playbook-configs/slc/datawolfWorkflow.config.prod.json
- playbook-configs/slc/globals.config.dev.json
- playbook-configs/slc/globals.config.prod.json
- playbook-configs/slc/map.config.json
- templates/playbook/configmap.yaml
- templates/playbook/deployment.yaml
- updated config map to wire in new workflow configs
- updated the playbook-configs
> 387 release incore playbook 061 and update config for each city playbooks

- Chart.yaml
- README.md
- playbook-configs/galveston/datawolfWorkflow.config.prod.json
- playbook-configs/galveston/globals.config.prod.json
Also change the max condition to be 14; beyond 14 it will trigger the 250 max error.
> Release 1.25.2

- Chart.yaml
- README.md
- playbook-configs/galveston/datawolfWorkflow.config.prod.json
Conclusion, 14 CPUs is the fastest.
~~WIP playing with different cpu numbers and calculate time.~~
> configure cpu numbers

- CHANGELOG.md
- Chart.lock
- Chart.yaml
- templates/configmap.yaml
- templates/doc-api/deployment.yaml
- templates/doc-incore/deployment.yaml
- templates/doc-pyincore-data/deployment.yaml
- templates/doc-pyincore-viz/deployment.yaml
- templates/doc-pyincore/deployment.yaml
- templates/frontend/deployment.yaml
- values.yaml
All the components were deployed in dev instance and they are sending the information to the google analytics
> Add config map for google analytics for incore ui and all the documentations

- CHANGELOG.md
- Chart.yaml
The PR is a minor release to correct the chart version number
> Release 1.30.2

- CHANGELOG.md
- Chart.yaml
- templates/auth/deployment.yaml
This should fix the new user can't get space and quota issue --> downstream it should fix the new user can't spawn incore-lab issue.
> use correct mongodb

- CHANGELOG.md
- Chart.lock
- Chart.yaml
- playbook-configs/galveston/globals.config.dev.json
- playbook-configs/galveston/globals.config.prod.json
- playbook-configs/joplin/globals.config.dev.json
- playbook-configs/joplin/globals.config.prod.json
- playbook-configs/slc/globals.config.dev.json
- playbook-configs/slc/globals.config.prod.json
- templates/auth/deployment.yaml
- values.yaml
> Release 1.31.0

- CHANGELOG.md
- Chart.yaml
- templates/NOTES.txt
- templates/secrets.yaml
- templates/svc-project/deployment.yaml
- templates/svc-project/ingress.yaml
- templates/svc-project/service.yaml
- templates/svc-space/deployment.yaml
- values.yaml
> Added project service

- CHANGELOG.md
- Chart.yaml
- studio/dependencyGraph.json
- templates/studio/configmap.yaml
- templates/studio/deployment.yaml
This PR adds ConfigMap for studio to inject dependency graph.
> add dependency graph config map

- CHANGELOG.md
- Chart.yaml
- values.yaml
This has to be deployed after the new datawolf chart get ready
> Added extra env vars for new datawolf for INCORE

- CHANGELOG.md
- Chart.yaml
- templates/cronjobs/keycloak-new-user-alert.yaml
This one is running on prod and it works as 8 am and 4 pm every weekday
> Changed new user alert cron job schedule to central time

- CHANGELOG.md
- Chart.yaml
- values.yaml
I need to add preflight options together with a few other methods to the cors for local development
> Project service allow cors method

- Chart.lock
- studio/dependencyGraph.json
- templates/studio/deployment.yaml
This PR fixes the mount path of config files and updates the dependencyGraph.json
> Incore-studio with updated config map

- CHANGELOG.md
- Chart.yaml
- studio/dependencyGraph.json
This PR updates the Dependency graph to add Utitlity tools.
> update dependency graph to add utility tools

- CHANGELOG.md
- Chart.yaml
- studio/dependencyGraph.json
Updates dependency graph for studio
> add new analyses to dependency graph

- CHANGELOG.md
- Chart.yaml
- values.yaml
Release 1.36.0 for IN-CORE release 6.2.0
> Release 1.36.0
